# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
permissions:
 contents: write
jobs:
 build:
  runs-on: ubuntu-latest
  permissions: write-all
  steps:
      - name: Checkout-step
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven    
      - uses: actions/checkout@v3
      - name: Build and Run Tests
        if: success() || failure() # always run even if the previous step fails
        #run: mvn --batch-mode --update-snapshots package
        run: |
          mvn test
          mkdir -p results
      - name: base64
        if: success() || failure() # always run even if the previous step fails
        run: |
           cat /home/runner/work/JunitOpenTestReporting/JunitOpenTestReporting/target/surefire-reports/TEST-com.mycompany.app.HelloTest.xml | sed '/property name/d' > /home/runner/work/JunitOpenTestReporting/JunitOpenTestReporting/target/surefire-reports/readthis.xml
           base64 /home/runner/work/JunitOpenTestReporting/JunitOpenTestReporting/target/surefire-reports/readthis.xml > /home/runner/work/JunitOpenTestReporting/JunitOpenTestReporting/target/surefire-reports/removed.xml
           my_var=$(cat /home/runner/work/JunitOpenTestReporting/JunitOpenTestReporting/target/surefire-reports/removed.xml | tr -d '\n')
           curl --request POST https://pulse-7.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d "projectId=106715" -d "testcycle=4119973" -d "result="$my_var""        
           echo $my_var
      - name: Updated64
        if: success() || failure() # always run even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: /home/runner/work/JunitOpenTestReporting/JunitOpenTestReporting/target/surefire-reports # or path/to/artifact
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
    
