# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
permissions:
 contents: write
jobs:
 build:
  runs-on: ubuntu-latest
  permissions: write-all
  steps:
      - name: Checkout-step
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven    
      - uses: actions/checkout@v3
      - name: Build and Run Tests
        #run: mvn --batch-mode --update-snapshots package
        run: mvn test

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: success() || failure() # always run even if the previous step fails
        run: echo Paul says Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: success() || failure() # always run even if the previous step fails
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
